# Generated by Django 3.0.1 on 2019-12-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('emailaddress', models.CharField(max_length=30)),
                ('emp_id', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=14)),
                ('confirmpassword', models.CharField(max_length=14)),
            ],
        ),
    ]
